# Generated by Django 4.2.2 on 2023-11-18 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='value',
        ),
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='blog_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
