# Generated by Django 4.2.2 on 2023-11-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
