# Generated by Django 4.2.2 on 2023-11-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_profile_view_count'),
        ('blogs', '0004_alter_comment_unique_together_delete_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('owner', 'blog')},
        ),
    ]
